const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('siaeAPI', {
  // Bridge control
  startBridge: () => ipcRenderer.invoke('bridge:start'),
  stopBridge: () => ipcRenderer.invoke('bridge:stop'),
  getBridgeStatus: () => ipcRenderer.invoke('bridge:status'),
  
  // Reader and card operations
  checkReader: () => ipcRenderer.invoke('bridge:checkReader'),
  readCard: () => ipcRenderer.invoke('bridge:readCard'),
  
  // SIAE operations
  computeSigillo: (data) => ipcRenderer.invoke('bridge:computeSigillo', data),
  
  // Logging
  getLogPath: () => ipcRenderer.invoke('app:getLogPath'),
  getLogs: () => ipcRenderer.invoke('app:getLogs'),
  getFullLogs: () => ipcRenderer.invoke('app:getFullLogs'),
  
  // Live log updates
  onLogEntry: (callback) => {
    ipcRenderer.on('log:entry', (event, entry) => callback(entry));
  },
  
  // Status updates from main process
  onStatusUpdate: (callback) => {
    ipcRenderer.on('status:update', (event, status) => callback(status));
  },
  
  // Remote Relay control
  getRelayConfig: () => ipcRenderer.invoke('relay:getConfig'),
  setRelayConfig: (config) => ipcRenderer.invoke('relay:setConfig', config),
  connectRelay: () => ipcRenderer.invoke('relay:connect'),
  disconnectRelay: () => ipcRenderer.invoke('relay:disconnect'),
  getRelayStatus: () => ipcRenderer.invoke('relay:status'),
  switchServer: (serverType) => ipcRenderer.invoke('relay:switchServer', serverType),
  
  // PIN verification (SIAE compliance)
  verifyPin: (pin) => ipcRenderer.invoke('pin:verify', pin),
  getPinStatus: () => ipcRenderer.invoke('pin:status'),
  setPin: (newPin) => ipcRenderer.invoke('pin:setPin', newPin),
  onPinRequired: (callback) => {
    ipcRenderer.on('pin:required', (event, data) => callback(data));
  },
  
  // Sigillo generated by server request
  onSigilloGenerated: (callback) => {
    ipcRenderer.on('sigillo:generated', (event, data) => callback(data));
  },
  
  // Platform info
  platform: process.platform,
  arch: process.arch
});
