// Event Four You - SIAE Lettore Renderer

document.addEventListener('DOMContentLoaded', () => {
  // Elements
  const btnConnect = document.getElementById('btn-connect');
  const btnCheckReader = document.getElementById('btn-check-reader');
  const btnReadCard = document.getElementById('btn-read-card');
  const btnToggleLogs = document.getElementById('btn-toggle-logs');
  const btnClearLogs = document.getElementById('btn-clear-logs');
  const btnExportLogs = document.getElementById('btn-export-logs');
  
  // Relay elements (auto-connect - no user input needed)
  const statusRelay = document.getElementById('status-relay');
  const serverSelect = document.getElementById('server-select');
  const relayInfoText = document.getElementById('relay-info-text');
  
  const statusBridge = document.getElementById('status-bridge');
  const statusReader = document.getElementById('status-reader');
  const statusCard = document.getElementById('status-card');
  
  const cardPanel = document.getElementById('card-panel');
  const sigilloPanel = document.getElementById('sigillo-panel');
  const logPanel = document.getElementById('log-panel');
  const logContent = document.getElementById('log-content');
  
  const sigilloForm = document.getElementById('sigillo-form');
  const sigilliList = document.getElementById('sigilli-list');

  // State
  let bridgeConnected = false;
  let sigilliHistory = []; // Store generated sigilli
  let readerConnected = false;
  let cardPresent = false;
  let relayConnected = false;
  let checkInterval = null;
  let pinDialogVisible = false;

  // Initialize
  init();
  
  // Listen for PIN required event (SIAE compliance)
  window.siaeAPI.onPinRequired((data) => {
    showPinDialog(data.reason);
  });

  // Listen for sigilli generated by server requests
  window.siaeAPI.onSigilloGenerated((data) => {
    addLog('info', `Sigillo generato (server): ${data.mac}`);
    
    // Add to history
    sigilliHistory.unshift({
      mac: data.mac,
      serialNumber: data.serialNumber,
      counter: data.counter,
      dateTime: data.dateTime ? new Date(data.dateTime) : new Date(),
      price: data.price || 0,
      source: data.source || 'server'
    });
    
    // Keep only last 50 sigilli
    if (sigilliHistory.length > 50) {
      sigilliHistory = sigilliHistory.slice(0, 50);
    }
    
    renderSigilliList();
  });

  async function init() {
    addLog('info', 'Applicazione avviata');
    
    // Set current datetime for sigillo form
    const now = new Date();
    const dateInput = document.getElementById('input-datetime');
    dateInput.value = now.toISOString().slice(0, 16);
    
    // Check initial bridge status
    const status = await window.siaeAPI.getBridgeStatus();
    addLog('info', `Bridge path: ${status.bridgePath || 'Non trovato'}`);
    
    // Load relay config
    await loadRelayConfig();
    
    // Setup live log listener
    window.siaeAPI.onLogEntry((entry) => {
      addLogEntry(entry);
    });
    
    // Setup status update listener
    window.siaeAPI.onStatusUpdate((status) => {
      updateRelayStatusUI(status.relayConnected);
    });
  }
  
  // Server selector event handler
  serverSelect.addEventListener('change', async (e) => {
    const serverType = e.target.value;
    addLog('info', `Cambio server a: ${serverType}`);
    updateStatus(statusRelay, 'warning', 'Cambio server...');
    
    try {
      const result = await window.siaeAPI.switchServer(serverType);
      if (result.success) {
        addLog('info', `✓ Server cambiato a ${serverType}`);
        updateRelayInfoText(serverType);
        // Wait a bit for reconnection
        setTimeout(async () => {
          const config = await window.siaeAPI.getRelayConfig();
          updateRelayStatusUI(config?.connected || false, serverType);
        }, 2000);
      } else {
        addLog('error', `Errore cambio server: ${result.error}`);
      }
    } catch (e) {
      addLog('error', `Errore cambio server: ${e.message}`);
    }
  });

  // Relay functions - auto-connect (no user input needed)
  async function loadRelayConfig() {
    try {
      const config = await window.siaeAPI.getRelayConfig();
      if (config) {
        // Set dropdown to current server type
        if (config.serverType) {
          serverSelect.value = config.serverType;
        }
        updateRelayInfoText(config.serverType || 'production');
        updateRelayStatusUI(config.connected, config.serverType || 'production');
        
        if (config.connected) {
          addLog('info', '✓ Connesso al server Event4U');
        } else {
          addLog('info', 'Connessione automatica in corso...');
          // Wait for auto-connect
          setTimeout(async () => {
            const newConfig = await window.siaeAPI.getRelayConfig();
            updateRelayStatusUI(newConfig?.connected || false, newConfig?.serverType || 'production');
          }, 3000);
        }
      }
    } catch (e) {
      addLog('error', `Errore connessione: ${e.message}`);
    }
  }
  
  function updateRelayInfoText(serverType) {
    if (serverType === 'development') {
      relayInfoText.textContent = 'Connesso al server di sviluppo (Replit)';
    } else {
      relayInfoText.textContent = 'Connesso a manage.eventfouryou.com';
    }
  }
  
  function updateRelayStatusUI(connected, serverType = 'production') {
    relayConnected = connected;
    const serverName = serverType === 'development' ? 'Sviluppo (Replit)' : 'Produzione';
    if (connected) {
      updateStatus(statusRelay, 'connected', `Connesso - ${serverName}`);
    } else {
      updateStatus(statusRelay, 'warning', `Connessione in corso - ${serverName}...`);
    }
  }

  // Event Handlers
  btnConnect.addEventListener('click', async () => {
    if (bridgeConnected) {
      await disconnectBridge();
    } else {
      await connectBridge();
    }
  });

  btnCheckReader.addEventListener('click', async () => {
    await checkReader();
  });

  btnReadCard.addEventListener('click', async () => {
    await readCard();
  });

  btnToggleLogs.addEventListener('click', () => {
    logPanel.classList.toggle('collapsed');
  });

  btnClearLogs.addEventListener('click', () => {
    logContent.innerHTML = '';
    addLog('info', 'Log cancellati');
  });

  btnExportLogs.addEventListener('click', async () => {
    const logs = await window.siaeAPI.getFullLogs();
    downloadText('siae-log.txt', logs);
  });

  sigilloForm.addEventListener('submit', async (e) => {
    e.preventDefault();
    await computeSigillo();
  });

  // Functions
  async function connectBridge() {
    btnConnect.disabled = true;
    btnConnect.innerHTML = '<span class="btn-icon">⏳</span> Connessione...';
    addLog('info', 'Connessione al bridge...');

    try {
      const result = await window.siaeAPI.startBridge();
      
      if (result.success) {
        bridgeConnected = true;
        updateStatus(statusBridge, 'connected', 'Connesso');
        btnConnect.innerHTML = '<span class="btn-icon">🔌</span> Disconnetti';
        btnCheckReader.disabled = false;
        addLog('info', '✓ Bridge connesso');
        
        // Start periodic check
        startPeriodicCheck();
        
        // Check reader immediately
        await checkReader();
      } else {
        throw new Error(result.error || 'Connessione fallita');
      }
    } catch (err) {
      addLog('error', `Errore connessione: ${err.message}`);
      updateStatus(statusBridge, 'error', 'Errore');
      btnConnect.innerHTML = '<span class="btn-icon">🔌</span> Riprova';
    }
    
    btnConnect.disabled = false;
  }

  async function disconnectBridge() {
    stopPeriodicCheck();
    
    await window.siaeAPI.stopBridge();
    bridgeConnected = false;
    readerConnected = false;
    cardPresent = false;
    
    updateStatus(statusBridge, '', 'Non connesso');
    updateStatus(statusReader, '', 'Non rilevato');
    updateStatus(statusCard, '', 'Non inserita');
    
    btnConnect.innerHTML = '<span class="btn-icon">🔌</span> Connetti Bridge';
    btnCheckReader.disabled = true;
    cardPanel.style.display = 'none';
    sigilloPanel.style.display = 'none';
    
    addLog('info', 'Bridge disconnesso');
  }

  async function checkReader() {
    if (!bridgeConnected) return;
    
    try {
      const result = await window.siaeAPI.checkReader();
      
      if (result.success) {
        readerConnected = result.readerConnected;
        cardPresent = result.cardPresent;
        
        if (readerConnected) {
          updateStatus(statusReader, 'connected', 'Connesso');
        } else {
          updateStatus(statusReader, 'error', 'Non rilevato');
        }
        
        if (cardPresent) {
          updateStatus(statusCard, 'connected', 'Carta inserita');
          cardPanel.style.display = 'block';
          sigilloPanel.style.display = 'block';
          addLog('info', `✓ Carta rilevata (slot ${result.slot})`);
        } else {
          updateStatus(statusCard, 'warning', 'Non inserita');
          cardPanel.style.display = 'none';
          sigilloPanel.style.display = 'none';
        }
      } else {
        if (result.error && result.error.includes('libSIAE')) {
          updateStatus(statusReader, 'error', 'DLL mancante');
          addLog('error', 'libSIAE.dll non trovata!');
        } else {
          updateStatus(statusReader, 'error', 'Errore');
          addLog('error', result.error);
        }
      }
    } catch (err) {
      addLog('error', `Errore check: ${err.message}`);
    }
  }

  async function readCard() {
    if (!cardPresent) {
      addLog('warn', 'Nessuna carta presente');
      return;
    }

    btnReadCard.disabled = true;
    btnReadCard.innerHTML = '<span class="btn-icon">⏳</span> Lettura...';
    addLog('info', 'Lettura carta in corso...');

    try {
      const result = await window.siaeAPI.readCard();
      
      if (result.success) {
        document.getElementById('card-serial').textContent = result.serialNumber;
        document.getElementById('card-counter').textContent = result.counter;
        document.getElementById('card-balance').textContent = result.balance;
        document.getElementById('card-keyid').textContent = result.keyId;
        
        addLog('info', `✓ Carta letta - SN: ${result.serialNumber}`);
      } else {
        addLog('error', `Errore lettura: ${result.error}`);
        // Card might have been removed
        await checkReader();
      }
    } catch (err) {
      addLog('error', `Errore: ${err.message}`);
    }

    btnReadCard.disabled = false;
    btnReadCard.innerHTML = '<span class="btn-icon">📖</span> Leggi Carta';
  }

  async function computeSigillo() {
    if (!cardPresent) {
      addLog('warn', 'Inserire la carta per generare il sigillo');
      return;
    }

    const priceInput = document.getElementById('input-price');
    const dateInput = document.getElementById('input-datetime');
    
    const price = parseFloat(priceInput.value) || 0;
    const dateTime = dateInput.value ? new Date(dateInput.value) : new Date();
    
    addLog('info', `Generazione sigillo: €${price.toFixed(2)}...`);
    
    try {
      const result = await window.siaeAPI.computeSigillo({
        price: price,
        dateTime: dateTime.toISOString()
      });
      
      if (result.success) {
        // Add to history list
        const sigillo = {
          mac: result.sigillo.mac,
          serial: result.sigillo.serialNumber,
          counter: result.sigillo.counter,
          price: price,
          dateTime: dateTime
        };
        sigilliHistory.unshift(sigillo); // Add to top
        renderSigilliList();
        
        addLog('info', `✓ Sigillo generato - MAC: ${result.sigillo.mac}`);
        
        // Clear price input for next
        document.getElementById('input-price').value = '';
        document.getElementById('input-price').focus();
      } else {
        addLog('error', `Errore sigillo: ${result.error}`);
      }
    } catch (err) {
      addLog('error', `Errore: ${err.message}`);
    }
  }
  
  function renderSigilliList() {
    if (sigilliHistory.length === 0) {
      sigilliList.innerHTML = '<div class="sigilli-empty">Nessun sigillo generato</div>';
      return;
    }
    
    sigilliList.innerHTML = sigilliHistory.map((s, index) => {
      let timeStr = '--:--';
      try {
        if (s.dateTime instanceof Date && !isNaN(s.dateTime)) {
          timeStr = s.dateTime.toLocaleTimeString('it-IT', { hour: '2-digit', minute: '2-digit' });
        }
      } catch (e) { /* fallback to --:-- */ }
      
      return `
        <div class="sigillo-entry">
          <div class="sigillo-entry-info">
            <span class="sigillo-entry-mac">${escapeHtml(s.mac || '-')}</span>
            <span class="sigillo-entry-details">#${s.counter || 0} · ${timeStr}</span>
          </div>
          <span class="sigillo-entry-price">€${(s.price || 0).toFixed(2)}</span>
        </div>
      `;
    }).join('');
  }

  function startPeriodicCheck() {
    stopPeriodicCheck();
    checkInterval = setInterval(async () => {
      if (bridgeConnected) {
        await checkReader();
      }
    }, 3000);
  }

  function stopPeriodicCheck() {
    if (checkInterval) {
      clearInterval(checkInterval);
      checkInterval = null;
    }
  }

  function updateStatus(element, status, text) {
    element.className = 'status-item ' + status;
    element.querySelector('.status-value').textContent = text;
  }

  function addLog(level, message) {
    addLogEntry({
      timestamp: new Date().toISOString(),
      level: level,
      message: message
    });
  }

  function addLogEntry(entry) {
    const div = document.createElement('div');
    div.className = `log-entry log-${entry.level}`;
    
    const time = new Date(entry.timestamp);
    const timeStr = time.toLocaleTimeString('it-IT');
    
    div.innerHTML = `
      <span class="log-time">${timeStr}</span>
      <span class="log-message">${escapeHtml(entry.message)}</span>
    `;
    
    logContent.appendChild(div);
    logContent.scrollTop = logContent.scrollHeight;
    
    // Keep only last 200 entries
    while (logContent.children.length > 200) {
      logContent.removeChild(logContent.firstChild);
    }
  }

  function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }

  function downloadText(filename, text) {
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }
  
  // ============================================
  // PIN Dialog (SIAE Compliance)
  // ============================================
  
  function showPinDialog(reason) {
    if (pinDialogVisible) return;
    pinDialogVisible = true;
    
    addLog('warn', '⚠️ SIAE: Richiesta verifica PIN');
    
    // Create overlay
    const overlay = document.createElement('div');
    overlay.id = 'pin-overlay';
    overlay.style.cssText = `
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.8);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 10000;
    `;
    
    // Create dialog
    const dialog = document.createElement('div');
    dialog.style.cssText = `
      background: linear-gradient(145deg, #2d2d3a, #1e1e28);
      border-radius: 16px;
      padding: 32px;
      width: 400px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.5);
      border: 1px solid rgba(255,255,255,0.1);
    `;
    
    dialog.innerHTML = `
      <div style="text-align: center; margin-bottom: 24px;">
        <div style="font-size: 48px; margin-bottom: 16px;">🔐</div>
        <h2 style="color: #ff9800; margin: 0 0 8px 0; font-size: 20px;">Verifica PIN SIAE</h2>
        <p style="color: #999; margin: 0; font-size: 14px;">${reason || 'Inserire il PIN per continuare'}</p>
      </div>
      <div style="margin-bottom: 24px;">
        <input type="password" id="pin-input" maxlength="12" 
          style="width: 100%; padding: 16px; font-size: 24px; text-align: center; 
          letter-spacing: 6px; background: #1a1a24; border: 2px solid #444;
          border-radius: 8px; color: white; box-sizing: border-box;"
          placeholder="••••••" autofocus
          pattern="[0-9]*" inputmode="numeric">
        <p id="pin-error" style="color: #f44336; margin: 8px 0 0 0; font-size: 13px; display: none;">
          PIN errato. Riprova.
        </p>
      </div>
      <div style="display: flex; gap: 12px;">
        <button id="pin-cancel" style="flex: 1; padding: 14px; background: #444; 
          border: none; border-radius: 8px; color: white; font-size: 15px; cursor: pointer;">
          Annulla
        </button>
        <button id="pin-submit" style="flex: 1; padding: 14px; 
          background: linear-gradient(135deg, #4caf50, #388e3c);
          border: none; border-radius: 8px; color: white; font-size: 15px; 
          cursor: pointer; font-weight: 600;">
          Conferma
        </button>
      </div>
      <p style="text-align: center; color: #666; font-size: 12px; margin-top: 16px;">
        Inserisci il PIN della tua carta SIAE
      </p>
    `;
    
    overlay.appendChild(dialog);
    document.body.appendChild(overlay);
    
    const pinInput = document.getElementById('pin-input');
    const pinError = document.getElementById('pin-error');
    const pinSubmit = document.getElementById('pin-submit');
    const pinCancel = document.getElementById('pin-cancel');
    
    pinInput.focus();
    
    async function verifyPin() {
      const pin = pinInput.value.replace(/\D/g, ''); // Solo numeri
      if (!pin || pin.length < 4) {
        pinError.textContent = 'PIN deve essere di almeno 4 cifre';
        pinError.style.display = 'block';
        return;
      }
      
      pinSubmit.disabled = true;
      pinSubmit.textContent = 'Verifica...';
      
      try {
        const result = await window.siaeAPI.verifyPin(pin);
        console.log('PIN verification result:', result);
        
        if (result && result.success) {
          addLog('info', '✓ PIN verificato correttamente');
          closePinDialog();
        } else {
          // Check if PIN is blocked (error code 0x6983 or 0 retries)
          const isBlocked = result?.errorCode === 0x6983 || 
                           result?.pinRetriesRemaining === 0 ||
                           (result?.error && result.error.toLowerCase().includes('bloccato'));
          
          if (isBlocked) {
            closePinDialog();
            addLog('error', 'PIN bloccato! Necessario sblocco con PUK');
            setTimeout(() => {
              window.showPukUnlockDialog && window.showPukUnlockDialog();
            }, 300);
          } else {
            let errorMsg = result?.error || 'PIN errato';
            if (result?.pinRetriesRemaining !== undefined && result?.pinRetriesRemaining !== null) {
              errorMsg += ` (${result.pinRetriesRemaining} tentativi rimanenti)`;
            }
            pinError.textContent = errorMsg;
            pinError.style.display = 'block';
            pinInput.value = '';
            pinInput.focus();
            addLog('error', errorMsg);
          }
        }
      } catch (err) {
        console.error('PIN verification error:', err);
        pinError.textContent = 'Errore verifica: ' + err.message;
        pinError.style.display = 'block';
        addLog('error', 'Errore verifica PIN: ' + err.message);
      } finally {
        pinSubmit.disabled = false;
        pinSubmit.textContent = 'Conferma';
      }
    }
    
    function closePinDialog() {
      console.log('Closing PIN dialog...');
      try {
        if (overlay && overlay.parentNode) {
          overlay.parentNode.removeChild(overlay);
        }
      } catch (e) {
        console.error('Error removing overlay:', e);
      }
      pinDialogVisible = false;
      console.log('PIN dialog closed, pinDialogVisible =', pinDialogVisible);
    }
    
    pinSubmit.addEventListener('click', verifyPin);
    pinInput.addEventListener('keypress', (e) => {
      if (e.key === 'Enter') verifyPin();
    });
    pinCancel.addEventListener('click', () => {
      addLog('warn', 'Verifica PIN annullata - operazioni bloccate');
      closePinDialog();
    });
  }
  
  // ============================================
  // PIN Change Dialog
  // ============================================
  
  const btnChangePin = document.getElementById('btn-change-pin');
  if (btnChangePin) {
    btnChangePin.addEventListener('click', showChangePinDialog);
  }
  
  function showChangePinDialog() {
    addLog('info', '🔑 Apertura dialog cambio PIN');
    
    // Create overlay
    const overlay = document.createElement('div');
    overlay.id = 'change-pin-overlay';
    overlay.style.cssText = `
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.8);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 10000;
    `;
    
    // Create dialog
    const dialog = document.createElement('div');
    dialog.style.cssText = `
      background: linear-gradient(145deg, #2d2d3a, #1e1e28);
      border-radius: 16px;
      padding: 32px;
      width: 420px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.5);
      border: 1px solid rgba(255,255,255,0.1);
    `;
    
    dialog.innerHTML = `
      <div style="text-align: center; margin-bottom: 24px;">
        <div style="font-size: 48px; margin-bottom: 16px;">🔑</div>
        <h2 style="color: #2196f3; margin: 0 0 8px 0; font-size: 20px;">Cambia PIN Carta SIAE</h2>
        <p style="color: #999; margin: 0; font-size: 14px;">Inserisci il PIN attuale e il nuovo PIN</p>
      </div>
      <div style="margin-bottom: 16px;">
        <label style="display: block; color: #ccc; margin-bottom: 8px; font-size: 13px;">PIN Attuale</label>
        <input type="password" id="change-pin-old" maxlength="12" 
          style="width: 100%; padding: 14px; font-size: 20px; text-align: center; 
          letter-spacing: 6px; background: #1a1a24; border: 2px solid #444;
          border-radius: 8px; color: white; box-sizing: border-box;"
          placeholder="••••••" autofocus
          pattern="[0-9]*" inputmode="numeric">
      </div>
      <div style="margin-bottom: 16px;">
        <label style="display: block; color: #ccc; margin-bottom: 8px; font-size: 13px;">Nuovo PIN</label>
        <input type="password" id="change-pin-new" maxlength="12" 
          style="width: 100%; padding: 14px; font-size: 20px; text-align: center; 
          letter-spacing: 6px; background: #1a1a24; border: 2px solid #444;
          border-radius: 8px; color: white; box-sizing: border-box;"
          placeholder="••••••"
          pattern="[0-9]*" inputmode="numeric">
      </div>
      <div style="margin-bottom: 24px;">
        <label style="display: block; color: #ccc; margin-bottom: 8px; font-size: 13px;">Conferma Nuovo PIN</label>
        <input type="password" id="change-pin-confirm" maxlength="12" 
          style="width: 100%; padding: 14px; font-size: 20px; text-align: center; 
          letter-spacing: 6px; background: #1a1a24; border: 2px solid #444;
          border-radius: 8px; color: white; box-sizing: border-box;"
          placeholder="••••••"
          pattern="[0-9]*" inputmode="numeric">
        <p id="change-pin-error" style="color: #f44336; margin: 8px 0 0 0; font-size: 13px; display: none;"></p>
      </div>
      <div style="display: flex; gap: 12px;">
        <button id="change-pin-cancel" style="flex: 1; padding: 14px; background: #444; 
          border: none; border-radius: 8px; color: white; font-size: 15px; cursor: pointer;">
          Annulla
        </button>
        <button id="change-pin-submit" style="flex: 1; padding: 14px; 
          background: linear-gradient(135deg, #2196f3, #1976d2);
          border: none; border-radius: 8px; color: white; font-size: 15px; 
          cursor: pointer; font-weight: 600;">
          Cambia PIN
        </button>
      </div>
      <p style="text-align: center; color: #ff9800; font-size: 12px; margin-top: 16px;">
        ⚠️ Ricorda il nuovo PIN, non può essere recuperato
      </p>
    `;
    
    overlay.appendChild(dialog);
    document.body.appendChild(overlay);
    
    const oldPinInput = document.getElementById('change-pin-old');
    const newPinInput = document.getElementById('change-pin-new');
    const confirmPinInput = document.getElementById('change-pin-confirm');
    const errorEl = document.getElementById('change-pin-error');
    const submitBtn = document.getElementById('change-pin-submit');
    const cancelBtn = document.getElementById('change-pin-cancel');
    
    oldPinInput.focus();
    
    function closeDialog() {
      if (overlay && overlay.parentNode) {
        overlay.parentNode.removeChild(overlay);
      }
    }
    
    async function changePin() {
      const oldPin = oldPinInput.value.replace(/\D/g, '');
      const newPin = newPinInput.value.replace(/\D/g, '');
      const confirmPin = confirmPinInput.value.replace(/\D/g, '');
      
      // Validation
      if (!oldPin || oldPin.length < 4) {
        errorEl.textContent = 'PIN attuale deve essere di almeno 4 cifre';
        errorEl.style.display = 'block';
        return;
      }
      if (!newPin || newPin.length < 4) {
        errorEl.textContent = 'Nuovo PIN deve essere di almeno 4 cifre';
        errorEl.style.display = 'block';
        return;
      }
      if (newPin !== confirmPin) {
        errorEl.textContent = 'I nuovi PIN non corrispondono';
        errorEl.style.display = 'block';
        return;
      }
      if (oldPin === newPin) {
        errorEl.textContent = 'Il nuovo PIN deve essere diverso dall\'attuale';
        errorEl.style.display = 'block';
        return;
      }
      
      submitBtn.disabled = true;
      submitBtn.textContent = 'Cambio in corso...';
      errorEl.style.display = 'none';
      
      try {
        const result = await window.siaeAPI.changePin(oldPin, newPin);
        console.log('PIN change result:', result);
        
        if (result && result.success) {
          addLog('info', '✓ PIN cambiato correttamente');
          closeDialog();
          // Show success message
          alert('PIN cambiato con successo!');
        } else {
          errorEl.textContent = result?.error || 'Errore cambio PIN';
          errorEl.style.display = 'block';
          addLog('error', result?.error || 'Errore cambio PIN');
        }
      } catch (err) {
        console.error('PIN change error:', err);
        errorEl.textContent = 'Errore: ' + err.message;
        errorEl.style.display = 'block';
        addLog('error', 'Errore cambio PIN: ' + err.message);
      } finally {
        submitBtn.disabled = false;
        submitBtn.textContent = 'Cambia PIN';
      }
    }
    
    submitBtn.addEventListener('click', changePin);
    confirmPinInput.addEventListener('keypress', (e) => {
      if (e.key === 'Enter') changePin();
    });
    cancelBtn.addEventListener('click', () => {
      addLog('info', 'Cambio PIN annullato');
      closeDialog();
    });
    
    // Close on escape
    overlay.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') {
        closeDialog();
      }
    });
  }
  
  // ============================================
  // PUK Unlock Dialog - For blocked cards
  // ============================================
  
  function showPukUnlockDialog(retriesRemaining = null) {
    addLog('warn', '🔓 Apertura dialog sblocco PUK');
    
    const overlay = document.createElement('div');
    overlay.id = 'puk-unlock-overlay';
    overlay.style.cssText = `
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.85);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 10000;
    `;
    
    const dialog = document.createElement('div');
    dialog.style.cssText = `
      background: linear-gradient(145deg, #2d2d3a, #1e1e28);
      border-radius: 16px;
      padding: 32px;
      width: 440px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.5);
      border: 2px solid #f44336;
    `;
    
    const retriesText = retriesRemaining !== null 
      ? `<p style="color: #f44336; text-align: center; margin-top: 8px; font-size: 13px;">⚠️ Tentativi PUK rimanenti: ${retriesRemaining}</p>` 
      : '';
    
    dialog.innerHTML = `
      <div style="text-align: center; margin-bottom: 24px;">
        <div style="font-size: 48px; margin-bottom: 16px;">🔓</div>
        <h2 style="color: #f44336; margin: 0 0 8px 0; font-size: 20px;">Sblocco Carta con PUK</h2>
        <p style="color: #999; margin: 0; font-size: 14px;">Il PIN è bloccato. Usa il PUK per sbloccarlo.</p>
        ${retriesText}
      </div>
      <div style="margin-bottom: 16px;">
        <label style="display: block; color: #ccc; margin-bottom: 8px; font-size: 13px;">Codice PUK (8 cifre)</label>
        <input type="password" id="puk-input" maxlength="8" 
          style="width: 100%; padding: 14px; font-size: 22px; text-align: center; 
          letter-spacing: 8px; background: #1a1a24; border: 2px solid #f44336;
          border-radius: 8px; color: white; box-sizing: border-box;"
          placeholder="••••••••" autofocus
          pattern="[0-9]*" inputmode="numeric">
      </div>
      <div style="margin-bottom: 16px;">
        <label style="display: block; color: #ccc; margin-bottom: 8px; font-size: 13px;">Nuovo PIN (4-8 cifre)</label>
        <input type="password" id="puk-new-pin" maxlength="8" 
          style="width: 100%; padding: 14px; font-size: 20px; text-align: center; 
          letter-spacing: 6px; background: #1a1a24; border: 2px solid #444;
          border-radius: 8px; color: white; box-sizing: border-box;"
          placeholder="••••••"
          pattern="[0-9]*" inputmode="numeric">
      </div>
      <div style="margin-bottom: 24px;">
        <label style="display: block; color: #ccc; margin-bottom: 8px; font-size: 13px;">Conferma nuovo PIN</label>
        <input type="password" id="puk-confirm-pin" maxlength="8" 
          style="width: 100%; padding: 14px; font-size: 20px; text-align: center; 
          letter-spacing: 6px; background: #1a1a24; border: 2px solid #444;
          border-radius: 8px; color: white; box-sizing: border-box;"
          placeholder="••••••"
          pattern="[0-9]*" inputmode="numeric">
        <p id="puk-error" style="color: #f44336; margin: 8px 0 0 0; font-size: 13px; display: none;">
          PUK errato
        </p>
      </div>
      <div style="display: flex; gap: 12px;">
        <button id="puk-cancel" style="flex: 1; padding: 14px; background: #444; 
          border: none; border-radius: 8px; color: white; font-size: 15px; cursor: pointer;">
          Annulla
        </button>
        <button id="puk-submit" style="flex: 1; padding: 14px; 
          background: linear-gradient(135deg, #ff5722, #e64a19);
          border: none; border-radius: 8px; color: white; font-size: 15px; 
          cursor: pointer; font-weight: 600;">
          Sblocca Carta
        </button>
      </div>
      <p style="text-align: center; color: #888; font-size: 11px; margin-top: 16px;">
        Il PUK è fornito insieme alla Smart Card. Se non lo hai, contatta SIAE.
      </p>
    `;
    
    overlay.appendChild(dialog);
    document.body.appendChild(overlay);
    
    const pukInput = document.getElementById('puk-input');
    const newPinInput = document.getElementById('puk-new-pin');
    const confirmPinInput = document.getElementById('puk-confirm-pin');
    const errorEl = document.getElementById('puk-error');
    const submitBtn = document.getElementById('puk-submit');
    const cancelBtn = document.getElementById('puk-cancel');
    
    pukInput.focus();
    
    function closeDialog() {
      if (overlay && overlay.parentNode) {
        overlay.parentNode.removeChild(overlay);
      }
    }
    
    async function unlockWithPuk() {
      const puk = pukInput.value.replace(/\D/g, '');
      const newPin = newPinInput.value.replace(/\D/g, '');
      const confirmPin = confirmPinInput.value.replace(/\D/g, '');
      
      if (!puk || puk.length !== 8) {
        errorEl.textContent = 'PUK deve essere esattamente 8 cifre';
        errorEl.style.display = 'block';
        return;
      }
      if (!newPin || newPin.length < 4) {
        errorEl.textContent = 'Nuovo PIN deve essere di almeno 4 cifre';
        errorEl.style.display = 'block';
        return;
      }
      if (newPin !== confirmPin) {
        errorEl.textContent = 'I PIN non corrispondono';
        errorEl.style.display = 'block';
        return;
      }
      
      submitBtn.disabled = true;
      submitBtn.textContent = 'Sblocco in corso...';
      errorEl.style.display = 'none';
      
      try {
        const result = await window.siaeAPI.unlockWithPuk(puk, newPin);
        console.log('PUK unlock result:', result);
        
        if (result && result.unlocked) {
          addLog('info', '✓ Carta sbloccata con successo');
          closeDialog();
          alert('Carta sbloccata! Nuovo PIN impostato.');
        } else {
          let errorMsg = result?.error || 'Errore sblocco';
          const retries = result?.pukRetriesRemaining ?? result?.retriesRemaining;
          if (retries !== undefined && retries !== null) {
            errorMsg += ` (${retries} tentativi rimanenti)`;
          }
          errorEl.textContent = errorMsg;
          errorEl.style.display = 'block';
          addLog('error', errorMsg);
          
          if (retries === 0) {
            errorEl.textContent = 'PUK BLOCCATO! La carta è inutilizzabile. Contatta SIAE.';
          }
        }
      } catch (err) {
        console.error('PUK unlock error:', err);
        errorEl.textContent = 'Errore: ' + err.message;
        errorEl.style.display = 'block';
        addLog('error', 'Errore sblocco PUK: ' + err.message);
      } finally {
        submitBtn.disabled = false;
        submitBtn.textContent = 'Sblocca Carta';
      }
    }
    
    submitBtn.addEventListener('click', unlockWithPuk);
    confirmPinInput.addEventListener('keypress', (e) => {
      if (e.key === 'Enter') unlockWithPuk();
    });
    cancelBtn.addEventListener('click', () => {
      addLog('warn', 'Sblocco PUK annullato');
      closeDialog();
    });
    
    overlay.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') {
        closeDialog();
      }
    });
  }
  
  // Expose the PUK dialog globally so it can be triggered from PIN error
  window.showPukUnlockDialog = showPukUnlockDialog;
});
